/**
 * workflow/defaults.ts — Default workflow configuration.
 */
import {
  ACTION,
  DEFAULT_ROLES,
  EXECUTION_MODE,
  REVIEW_CHECK,
  REVIEW_POLICY,
  STATE_TYPE,
  TEST_POLICY,
  WORKFLOW_EVENT,
  WORKFLOW_STATE_COLORS,
  WORKFLOW_STATE_KEYS,
  WORKFLOW_STATE_LABELS,
} from "./const.js";
import type { BuiltInWorkflowConfig } from "./types.js";

export const DEFAULT_WORKFLOW: BuiltInWorkflowConfig = {
  initial: WORKFLOW_STATE_KEYS.PLANNING,
  reviewPolicy: REVIEW_POLICY.HUMAN,
  testPolicy: TEST_POLICY.SKIP,
  roleExecution: EXECUTION_MODE.PARALLEL,
  states: {
    // ── Main pipeline (happy path) ──────────────────────────────
    [WORKFLOW_STATE_KEYS.PLANNING]: {
      type: STATE_TYPE.HOLD,
      label: WORKFLOW_STATE_LABELS.PLANNING,
      color: WORKFLOW_STATE_COLORS.PLANNING,
      on: { [WORKFLOW_EVENT.APPROVE]: { target: WORKFLOW_STATE_KEYS.TODO } },
    },
    [WORKFLOW_STATE_KEYS.TODO]: {
      type: STATE_TYPE.QUEUE,
      role: DEFAULT_ROLES.DEVELOPER,
      label: WORKFLOW_STATE_LABELS.TODO,
      color: WORKFLOW_STATE_COLORS.TODO,
      priority: 1,
      on: { [WORKFLOW_EVENT.PICKUP]: { target: WORKFLOW_STATE_KEYS.DOING } },
    },
    [WORKFLOW_STATE_KEYS.DOING]: {
      type: STATE_TYPE.ACTIVE,
      role: DEFAULT_ROLES.DEVELOPER,
      label: WORKFLOW_STATE_LABELS.DOING,
      color: WORKFLOW_STATE_COLORS.DOING,
      on: {
        [WORKFLOW_EVENT.COMPLETE]: { target: WORKFLOW_STATE_KEYS.TO_REVIEW, actions: [ACTION.DETECT_PR] },
        [WORKFLOW_EVENT.BLOCKED]: { target: WORKFLOW_STATE_KEYS.REFINING },
      },
    },
    [WORKFLOW_STATE_KEYS.TO_REVIEW]: {
      type: STATE_TYPE.QUEUE,
      role: DEFAULT_ROLES.REVIEWER,
      label: WORKFLOW_STATE_LABELS.TO_REVIEW,
      color: WORKFLOW_STATE_COLORS.TO_REVIEW,
      priority: 2,
      check: REVIEW_CHECK.PR_APPROVED,
      on: {
        [WORKFLOW_EVENT.PICKUP]: { target: WORKFLOW_STATE_KEYS.REVIEWING },
        [WORKFLOW_EVENT.APPROVED]: { target: WORKFLOW_STATE_KEYS.TO_TEST, actions: [ACTION.MERGE_PR, ACTION.GIT_PULL] },
        [WORKFLOW_EVENT.SKIP]: { target: WORKFLOW_STATE_KEYS.TO_TEST, actions: [ACTION.MERGE_PR, ACTION.GIT_PULL] },
        [WORKFLOW_EVENT.MERGE_FAILED]: { target: WORKFLOW_STATE_KEYS.TO_IMPROVE },
        [WORKFLOW_EVENT.CHANGES_REQUESTED]: { target: WORKFLOW_STATE_KEYS.TO_IMPROVE },
        [WORKFLOW_EVENT.MERGE_CONFLICT]: { target: WORKFLOW_STATE_KEYS.TO_IMPROVE },
        [WORKFLOW_EVENT.PR_CLOSED]: { target: WORKFLOW_STATE_KEYS.REJECTED, actions: [ACTION.CLOSE_ISSUE] },
      },
    },
    [WORKFLOW_STATE_KEYS.REVIEWING]: {
      type: STATE_TYPE.ACTIVE,
      role: DEFAULT_ROLES.REVIEWER,
      label: WORKFLOW_STATE_LABELS.REVIEWING,
      color: WORKFLOW_STATE_COLORS.REVIEWING,
      on: {
        [WORKFLOW_EVENT.APPROVE]: { target: WORKFLOW_STATE_KEYS.TO_TEST, actions: [ACTION.MERGE_PR, ACTION.GIT_PULL] },
        [WORKFLOW_EVENT.REJECT]: { target: WORKFLOW_STATE_KEYS.TO_IMPROVE },
        [WORKFLOW_EVENT.BLOCKED]: { target: WORKFLOW_STATE_KEYS.REFINING },
      },
    },
    // ── Test phase (skipped by default via testPolicy: skip) ────
    [WORKFLOW_STATE_KEYS.TO_TEST]: {
      type: STATE_TYPE.QUEUE,
      role: DEFAULT_ROLES.TESTER,
      label: WORKFLOW_STATE_LABELS.TO_TEST,
      color: WORKFLOW_STATE_COLORS.TO_TEST,
      priority: 2,
      on: {
        [WORKFLOW_EVENT.PICKUP]: { target: WORKFLOW_STATE_KEYS.TESTING },
        [WORKFLOW_EVENT.SKIP]: { target: WORKFLOW_STATE_KEYS.DONE, actions: [ACTION.CLOSE_ISSUE] },
      },
    },
    [WORKFLOW_STATE_KEYS.TESTING]: {
      type: STATE_TYPE.ACTIVE,
      role: DEFAULT_ROLES.TESTER,
      label: WORKFLOW_STATE_LABELS.TESTING,
      color: WORKFLOW_STATE_COLORS.TESTING,
      on: {
        [WORKFLOW_EVENT.PASS]: { target: WORKFLOW_STATE_KEYS.DONE, actions: [ACTION.CLOSE_ISSUE] },
        [WORKFLOW_EVENT.FAIL]: { target: WORKFLOW_STATE_KEYS.TO_IMPROVE, actions: [ACTION.REOPEN_ISSUE] },
        [WORKFLOW_EVENT.REFINE]: { target: WORKFLOW_STATE_KEYS.REFINING },
        [WORKFLOW_EVENT.BLOCKED]: { target: WORKFLOW_STATE_KEYS.REFINING },
      },
    },
    [WORKFLOW_STATE_KEYS.DONE]: {
      type: STATE_TYPE.TERMINAL,
      label: WORKFLOW_STATE_LABELS.DONE,
      color: WORKFLOW_STATE_COLORS.DONE,
    },
    [WORKFLOW_STATE_KEYS.REJECTED]: {
      type: STATE_TYPE.TERMINAL,
      label: WORKFLOW_STATE_LABELS.REJECTED,
      color: WORKFLOW_STATE_COLORS.REJECTED,
    },

    // ── Side paths (loops back into main pipeline) ──────────────
    [WORKFLOW_STATE_KEYS.TO_IMPROVE]: {
      type: STATE_TYPE.QUEUE,
      role: DEFAULT_ROLES.DEVELOPER,
      label: WORKFLOW_STATE_LABELS.TO_IMPROVE,
      color: WORKFLOW_STATE_COLORS.TO_IMPROVE,
      priority: 3,
      on: { [WORKFLOW_EVENT.PICKUP]: { target: WORKFLOW_STATE_KEYS.DOING } },
    },
    [WORKFLOW_STATE_KEYS.REFINING]: {
      type: STATE_TYPE.HOLD,
      label: WORKFLOW_STATE_LABELS.REFINING,
      color: WORKFLOW_STATE_COLORS.REFINING,
      on: { [WORKFLOW_EVENT.APPROVE]: { target: WORKFLOW_STATE_KEYS.TODO } },
    },

    // ── Architect research pipeline ──────────────────────────────
    [WORKFLOW_STATE_KEYS.TO_RESEARCH]: {
      type: STATE_TYPE.QUEUE,
      role: DEFAULT_ROLES.ARCHITECT,
      label: WORKFLOW_STATE_LABELS.TO_RESEARCH,
      color: WORKFLOW_STATE_COLORS.TO_RESEARCH,
      priority: 1,
      on: { [WORKFLOW_EVENT.PICKUP]: { target: WORKFLOW_STATE_KEYS.RESEARCHING } },
    },
    [WORKFLOW_STATE_KEYS.RESEARCHING]: {
      type: STATE_TYPE.ACTIVE,
      role: DEFAULT_ROLES.ARCHITECT,
      label: WORKFLOW_STATE_LABELS.RESEARCHING,
      color: WORKFLOW_STATE_COLORS.RESEARCHING,
      on: {
        [WORKFLOW_EVENT.COMPLETE]: { target: WORKFLOW_STATE_KEYS.DONE, actions: [ACTION.CLOSE_ISSUE] },
        [WORKFLOW_EVENT.BLOCKED]: { target: WORKFLOW_STATE_KEYS.REFINING },
      },
    },

  },
};
