/**
 * Exposes the supported public API for DevClaw's pure domain semantics.
 * Consumers outside `lib/domain` import domain-owned contracts through this entrypoint.
 */
export type {
  ActiveIssueWorker,
  ArchivedIssueRecord,
  AttachmentDisposition,
  IssueArchiveReason,
  IssueCreationErrorCode,
  IssueCreationStatus,
  IssueIntegrityStatus,
  IssueProjectionState,
  IssueProviderId,
  IssueRuntimeState,
  PipelineNotificationState,
  ProviderMissingState,
} from "./issues/index.js";
export {
  ATTACHMENT_DISPOSITION,
  detectOwner,
  getOwnerLabel,
  isOwnedByOrUnclaimed,
  ISSUE_ARCHIVE_REASON,
  ISSUE_CREATION_ERROR,
  ISSUE_CREATION_STATUS,
  ISSUE_INTEGRITY_STATUS,
  ISSUE_PROVIDER,
  OWNER_LABEL_COLOR,
  OWNER_LABEL_PREFIX,
  PIPELINE_NOTIFICATION_STATUS,
} from "./issues/index.js";
export type {
  NotificationChannel,
  NotificationEndpoint,
  NotifyBindingRef,
} from "./notifications/index.js";
export {
  getNotifyLabel,
  isNotificationChannel,
  NOTIFICATION_CHANNEL,
  NOTIFY_LABEL_COLOR,
  NOTIFY_LABEL_PREFIX,
  resolveNotifyBinding,
} from "./notifications/index.js";
export type { Project, RoleWorkerState, SlotLocation, SlotState } from "./projects/index.js";
export {
  countActiveSlots,
  emptyRoleWorkerState,
  emptySlot,
  findFreeSlot,
  findSlotByIssue,
  reconcileSlots,
} from "./projects/index.js";
export type {
  BuiltInWorkflowConfig,
  CompletionEventMap,
  CompletionResult,
  CompletionRule,
  ExecutionMode,
  LabelDefinition,
  LevelId,
  ReviewCheckType,
  ReviewPolicy,
  RoleDefinition,
  RoleId,
  RoleLevelDefinition,
  RoutingLabel,
  StateDefinition,
  TestPolicy,
  TransitionAction,
  TransitionTarget,
  WorkflowConfig,
  WorkflowDefinition,
  WorkflowEvent,
  WorkflowLabel,
  WorkflowStateConfig,
  WorkflowStateKey,
} from "./workflow/index.js";
export {
  ACTION,
  COMPLETION_RESULT,
  DEFAULT_LEVELS,
  DEFAULT_RESULT_EMOJI,
  DEFAULT_ROLE_LABEL_COLOR,
  DEFAULT_ROLES,
  DEFAULT_WORKFLOW,
  detectRoleFromLabel,
  EXECUTION_MODE,
  findStateByLabel,
  findStateKeyByLabel,
  getActiveLabel,
  getAllQueueLabels,
  getCompletionEmoji,
  getCompletionRule,
  getCurrentStateLabel,
  getInitialStateLabel,
  getLabelColors,
  getNextStateDescription,
  getQueueLabels,
  getRevertLabel,
  getRoleLabelColor,
  getRoleLabels,
  getStateLabels,
  getStepRoutingLabels,
  hasReviewCheck,
  hasTestPhase,
  hasWorkflowStates,
  isBuiltInLevelId,
  isBuiltInRoleId,
  isCompletionResult,
  isFeedbackState,
  isReviewPolicy,
  isTestPolicy,
  isWorkflowEvent,
  producesReviewableWork,
  resolveReviewRouting,
  RESULT_EMOJI,
  REVIEW_CHECK,
  REVIEW_POLICY,
  ROLE_LABEL_COLORS,
  ROUTING_LABELS,
  STATE_TYPE,
  STEP_ROUTING_COLOR,
  TEST_POLICY,
  WORKFLOW_EVENT,
  WORKFLOW_STATE_COLORS,
  WORKFLOW_STATE_KEYS,
  WORKFLOW_STATE_LABELS,
} from "./workflow/index.js";
